
    create table categoria (
        id integer generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table cidade (
        estado_id integer,
        id integer generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table cliente (
        id integer generated by default as identity,
        tipo integer,
        cpf_ou_cnpj varchar(255),
        email varchar(255),
        nome varchar(255),
        primary key (id)
    );

    create table endereco (
        cidade_id integer,
        cliente_id integer,
        id integer generated by default as identity,
        bairro varchar(255),
        cep varchar(255),
        complemento varchar(255),
        logradouro varchar(255),
        numero varchar(255),
        primary key (id)
    );

    create table estado (
        id integer generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table produto (
        id integer generated by default as identity,
        preco float(53),
        nome varchar(255),
        primary key (id)
    );

    create table produto_categoria (
        categoria_id integer not null,
        produto_id integer not null
    );

    create table telefone (
        cliente_id integer not null,
        telefones varchar(255)
    );

    alter table if exists cidade 
       add constraint FKkworrwk40xj58kevvh3evi500 
       foreign key (estado_id) 
       references estado;

    alter table if exists endereco 
       add constraint FK8b1kcb3wucapb8dejshyn5fsx 
       foreign key (cidade_id) 
       references cidade;

    alter table if exists endereco 
       add constraint FK8s7ivtl4foyhrfam9xqom73n9 
       foreign key (cliente_id) 
       references cliente;

    alter table if exists produto_categoria 
       add constraint FKq3g33tp7xk2juh53fbw6y4y57 
       foreign key (categoria_id) 
       references categoria;

    alter table if exists produto_categoria 
       add constraint FK1c0y58d3n6x3m6euv2j3h64vt 
       foreign key (produto_id) 
       references produto;

    alter table if exists telefone 
       add constraint FK8aafha0njkoyoe3kvrwsy3g8u 
       foreign key (cliente_id) 
       references cliente;
