-- create table categoria (
--     id integer generated by default as identity,
--     nome varchar(255),
--     primary key (id)
-- );

CREATE TABLE categoria (
    id BIGINT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL
);