create table endereco (
    id integer generated by default as identity,
    bairro varchar(255),
    cep varchar(255),
    complemento varchar(255),
    logradouro varchar(255),
    numero varchar(255),
    primary key (id)
);